site_url : https://github.com/asalvadorc/BBDD_POSTGRES_DDL
site_name: BD - Bases de Dades
theme: 
  name: readthedocs
  logo: assets/logocaminas.png

extra_css:
  - css/extra.css
  - img/favicon.ico 

markdown_extensions:
  - admonition
  - tables    
  - attr_list
  - toc 
  - pymdownx.emoji
  - pymdownx.extra
  - pymdownx.superfences

nav:
  - POSTGRESQL - DDL :
    - 1. Introducció: 1_introducci.md
    - 2. DDL: 2_ddl.md
    - Exercicis del tot el tema: exercicis_de_tot_el_tema.md
  #- Consultes d'actualització:
  #  - 3. Consultes d'actualització: 33_consultes_dactualitzaci.md
  #  
    
